language: rust

arch:
  - amd64
  - ppc64le
  - arm64

os:
  - linux
  - osx
  - windows

rust:
  - nightly
  - beta
  - stable

script:
  - rustup component add rustfmt
  - rustup component add clippy
  - cargo fmt --all -- --check
  - cargo clippy --all-targets --all-features -- --deny warnings
  - cargo build --workspace --all-targets
  - cargo test --workspace --all-targets -- --nocapture
  - cargo bench --workspace --all-targets
  - cargo run --example asynchronous
  - cargo run --example synchronous
