[package]
name = "minitrace-jaeger"
version = "0.1.0"
authors = ["The TiKV Project Authors"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
minitrace = { path = "../.." }
rustracing_jaeger = "0.5.0"
thrift_codec = "0.1.1"
